platform :ios, '6.0'

pod 'vaml', :path => '../'
pod 'PixateFreestyle', '2.1'
pod 'ConstraintFormatter', git: 'https://github.com/greis/ConstraintFormatter.git'

target :VamlTests, :exclusive => true do
  pod 'Kiwi/XCTest', git: 'https://github.com/allending/Kiwi.git'
end
